import type { RawCard } from "./blazar";

/** Set 2. Kage Veil. The same dark fantasy, cut into a ninja war. Ten basic, four rare, one legendary per seal. */
export const KAGE_RAW: RawCard[] = [
  { id: "kg-leaf-fox", name: "Leaf Fox", faction: "elf", kind: "unit", cost: 1, atk: 1, hp: 1, rarity: "basic", set: "kage", tags: [], deathHeal: 1, text: "When this dies, you heal 1." },
  { id: "kg-silk-step", name: "Silk Step", faction: "elf", kind: "unit", cost: 1, atk: 2, hp: 1, rarity: "basic", set: "kage", tags: [], text: "A bare foot on wet bamboo." },
  { id: "kg-night-bow", name: "Night Bow", faction: "elf", kind: "unit", cost: 2, atk: 2, hp: 1, rarity: "basic", set: "kage", tags: ["haste"], text: "Haste. Can attack the turn it enters." },
  { id: "kg-reed-cloak", name: "Reed Cloak", faction: "elf", kind: "unit", cost: 2, atk: 1, hp: 3, rarity: "basic", set: "kage", tags: [], text: "The grove hides the blade." },
  { id: "kg-moon-needle", name: "Moon Needle", faction: "elf", kind: "spell", cost: 1, atk: 0, hp: 0, rarity: "basic", set: "kage", tags: [], play: { t: "hit", n: 2 }, text: "Deal 2 to a unit or a player." },
  { id: "kg-quiet-mend", name: "Quiet Mend", faction: "elf", kind: "spell", cost: 2, atk: 0, hp: 0, rarity: "basic", set: "kage", tags: [], play: { t: "healSelf", n: 2 }, text: "Heal 2." },
  { id: "kg-bamboo-snare", name: "Bamboo Snare", faction: "elf", kind: "trap", cost: 1, atk: 0, hp: 0, rarity: "basic", set: "kage", tags: [], trap: "glade", text: "Trap. When they attack: heal 2 and deal 1 to an attacker." },
  { id: "kg-twin-leaf", name: "Twin Leaf", faction: "elf", kind: "unit", cost: 3, atk: 2, hp: 4, rarity: "basic", set: "kage", tags: [], text: "Two shadows. One breath." },
  { id: "kg-grove-guard", name: "Grove Guard", faction: "elf", kind: "unit", cost: 3, atk: 2, hp: 4, rarity: "basic", set: "kage", tags: ["bulwark"], text: "Bulwark." },
  { id: "kg-petal-cut", name: "Petal Cut", faction: "elf", kind: "spell", cost: 2, atk: 0, hp: 0, rarity: "basic", set: "kage", tags: [], play: { t: "freeze" }, text: "Freeze a unit. It cannot attack on its next turn." },
  { id: "kg-crescent", name: "Crescent Shot", faction: "elf", kind: "unit", cost: 4, atk: 3, hp: 3, rarity: "rare", set: "kage", tags: ["haste"], text: "Haste. The bow fires before the moonlight returns." },
  { id: "kg-warden-veil", name: "Warden of the Veil", faction: "elf", kind: "unit", cost: 4, atk: 3, hp: 4, rarity: "rare", set: "kage", tags: [], play: { t: "healSelf", n: 2 }, text: "Play: heal 2." },
  { id: "kg-deep-mend", name: "Deep Mend", faction: "elf", kind: "spell", cost: 3, atk: 0, hp: 0, rarity: "rare", set: "kage", tags: [], play: { t: "healSelf", n: 4 }, text: "Heal 4." },
  { id: "kg-hidden-grove", name: "Hidden Grove", faction: "elf", kind: "trap", cost: 2, atk: 0, hp: 0, rarity: "rare", set: "kage", tags: [], trap: "horizon", text: "Trap. When they attack: deal 2 to an attacker and freeze it." },
  { id: "kg-lysara-kage", name: "Lysara of the Silent Moon", faction: "elf", kind: "unit", cost: 6, atk: 4, hp: 5, rarity: "legendary", set: "kage", tags: ["haste"], play: { t: "healSelf", n: 2 }, text: "Haste. Play: heal 2. Blonde, fair, and silent in the bamboo." },

  { id: "kg-rain-scout", name: "Rain Scout", faction: "human", kind: "unit", cost: 1, atk: 2, hp: 1, rarity: "basic", set: "kage", tags: [], text: "First steel in the rain." },
  { id: "kg-iron-squire", name: "Iron Squire", faction: "human", kind: "unit", cost: 1, atk: 1, hp: 2, rarity: "basic", set: "kage", tags: [], text: "A short blade and a kept oath." },
  { id: "kg-oath-wall", name: "Oath Wall", faction: "human", kind: "unit", cost: 2, atk: 1, hp: 4, rarity: "basic", set: "kage", tags: ["bulwark"], text: "Bulwark." },
  { id: "kg-night-medic", name: "Night Medic", faction: "human", kind: "unit", cost: 2, atk: 1, hp: 3, rarity: "basic", set: "kage", tags: [], play: { t: "healUnit", n: 2 }, text: "Play: heal an ally unit 2." },
  { id: "kg-steel-throw", name: "Steel Throw", faction: "human", kind: "spell", cost: 1, atk: 0, hp: 0, rarity: "basic", set: "kage", tags: [], play: { t: "hit", n: 2 }, text: "Deal 2 to a unit or a player." },
  { id: "kg-cloak-captain", name: "Cloak Captain", faction: "human", kind: "unit", cost: 2, atk: 2, hp: 2, rarity: "basic", set: "kage", tags: [], text: "The banner is folded. The oath is not." },
  { id: "kg-rain-line", name: "Rain Line", faction: "human", kind: "unit", cost: 3, atk: 3, hp: 3, rarity: "basic", set: "kage", tags: [], text: "Even steel. Even night." },
  { id: "kg-oath-blade", name: "Oath Blade", faction: "human", kind: "unit", cost: 3, atk: 3, hp: 2, rarity: "basic", set: "kage", tags: [], text: "One cut, then the line closes." },
  { id: "kg-banner-flash", name: "Banner Flash", faction: "human", kind: "spell", cost: 3, atk: 0, hp: 0, rarity: "basic", set: "kage", tags: [], play: { t: "rally" }, text: "Your units get +1 attack this turn." },
  { id: "kg-pike-night", name: "Pike Night", faction: "human", kind: "trap", cost: 2, atk: 0, hp: 0, rarity: "basic", set: "kage", tags: [], trap: "pikes", text: "Trap. When they attack: deal 3 to an attacker." },
  { id: "kg-kestrel-kage", name: "Kestrel in Shadow", faction: "human", kind: "unit", cost: 4, atk: 3, hp: 4, rarity: "rare", set: "kage", tags: [], play: { t: "buff", a: 1, h: 1 }, text: "Play: an ally unit gets +1/+1." },
  { id: "kg-marshal-mask", name: "Marshal Mask", faction: "human", kind: "unit", cost: 5, atk: 4, hp: 4, rarity: "rare", set: "kage", tags: [], play: { t: "hit", n: 2 }, text: "Play: deal 2 to a unit or a player." },
  { id: "kg-war-seal", name: "War Seal", faction: "human", kind: "spell", cost: 3, atk: 0, hp: 0, rarity: "rare", set: "kage", tags: [], play: { t: "hit", n: 3 }, text: "Deal 3 to a unit or a player." },
  { id: "kg-ambush-seal", name: "Ambush Seal", faction: "human", kind: "trap", cost: 2, atk: 0, hp: 0, rarity: "rare", set: "kage", tags: [], trap: "horizon", text: "Trap. When they attack: deal 2 to an attacker and freeze it." },
  { id: "kg-voss-kage", name: "Voss of the Night Oath", faction: "human", kind: "unit", cost: 6, atk: 5, hp: 5, rarity: "legendary", set: "kage", tags: [], play: { t: "hit", n: 2 }, text: "Play: deal 2 to a unit or a player. The oath does not need a sky." },

  { id: "kg-ember-rat", name: "Ember Rat", faction: "goblin", kind: "unit", cost: 1, atk: 1, hp: 1, rarity: "basic", set: "kage", tags: ["haste"], text: "Haste." },
  { id: "kg-alley-knife", name: "Alley Knife", faction: "goblin", kind: "unit", cost: 1, atk: 2, hp: 1, rarity: "basic", set: "kage", tags: [], text: "Already swinging." },
  { id: "kg-twin-stars", name: "Twin Stars", faction: "goblin", kind: "unit", cost: 1, atk: 1, hp: 1, rarity: "basic", set: "kage", tags: [], play: { t: "twin" }, text: "Play: if you control another Rixen, this gets +1/+1." },
  { id: "kg-scrap-dash", name: "Scrap Dash", faction: "goblin", kind: "unit", cost: 2, atk: 2, hp: 1, rarity: "basic", set: "kage", tags: [], text: "A mask of bent tin." },
  { id: "kg-cinder-cut", name: "Cinder Cut", faction: "goblin", kind: "unit", cost: 2, atk: 3, hp: 1, rarity: "basic", set: "kage", tags: [], text: "Fast, thin, and burning." },
  { id: "kg-mask-runner", name: "Mask Runner", faction: "goblin", kind: "unit", cost: 2, atk: 2, hp: 2, rarity: "basic", set: "kage", tags: [], text: "The grin is painted on." },
  { id: "kg-reckless-dash", name: "Reckless Dash", faction: "goblin", kind: "spell", cost: 1, atk: 0, hp: 0, rarity: "basic", set: "kage", tags: [], play: { t: "charge" }, text: "An ally unit gets +2 attack this turn and takes 1." },
  { id: "kg-boom-pouch", name: "Boom Pouch", faction: "goblin", kind: "unit", cost: 3, atk: 2, hp: 2, rarity: "basic", set: "kage", tags: [], play: { t: "boom" }, text: "Play: deal 1 to the opponent." },
  { id: "kg-drum-shadow", name: "Drum Shadow", faction: "goblin", kind: "unit", cost: 3, atk: 2, hp: 3, rarity: "basic", set: "kage", tags: [], aura: "goblinSwift", text: "Your Rixen can attack the turn they enter." },
  { id: "kg-cross-wire", name: "Cross Wire", faction: "goblin", kind: "trap", cost: 2, atk: 0, hp: 0, rarity: "basic", set: "kage", tags: [], trap: "cross", text: "Trap. When they attack: deal 2 to an attacker." },
  { id: "kg-void-blade", name: "Void Blade", faction: "goblin", kind: "unit", cost: 3, atk: 3, hp: 2, rarity: "rare", set: "kage", tags: ["haste"], text: "Haste." },
  { id: "kg-skarn-mask", name: "Skarn Mask", faction: "goblin", kind: "unit", cost: 5, atk: 4, hp: 4, rarity: "rare", set: "kage", tags: [], aura: "goblinAtk", text: "Your other Rixen have +1 attack." },
  { id: "kg-horde-star", name: "Horde Star", faction: "goblin", kind: "spell", cost: 4, atk: 0, hp: 0, rarity: "rare", set: "kage", tags: [], play: { t: "hit", n: 4 }, text: "Deal 4 to a unit or a player." },
  { id: "kg-pit-seal", name: "Pit Seal", faction: "goblin", kind: "trap", cost: 1, atk: 0, hp: 0, rarity: "rare", set: "kage", tags: [], trap: "snare", text: "Trap. When they attack: destroy an attacker with attack 2 or less." },
  { id: "kg-skarn-kage", name: "Skarn the Quiet Riot", faction: "goblin", kind: "unit", cost: 6, atk: 4, hp: 4, rarity: "legendary", set: "kage", tags: ["haste"], aura: "goblinAtk", text: "Haste. Your other Rixen have +1 attack." },

  { id: "kg-ion-scout", name: "Ion Scout", faction: "robot", kind: "unit", cost: 1, atk: 1, hp: 2, rarity: "basic", set: "kage", tags: [], text: "A lens under a hood of plates." },
  { id: "kg-clock-step", name: "Clock Step", faction: "robot", kind: "unit", cost: 2, atk: 2, hp: 2, rarity: "basic", set: "kage", tags: [], text: "The footfall is measured." },
  { id: "kg-plate-hood", name: "Plate Hood", faction: "robot", kind: "unit", cost: 2, atk: 1, hp: 4, rarity: "basic", set: "kage", tags: ["bulwark"], text: "Bulwark." },
  { id: "kg-weld-wisp", name: "Weld Wisp", faction: "robot", kind: "unit", cost: 2, atk: 1, hp: 2, rarity: "basic", set: "kage", tags: [], play: { t: "healUnit", n: 2 }, text: "Play: heal an ally unit 2." },
  { id: "kg-repair-line", name: "Repair Line", faction: "robot", kind: "unit", cost: 2, atk: 1, hp: 3, rarity: "basic", set: "kage", tags: [], text: "A stitch of cold light." },
  { id: "kg-overclock-spark", name: "Overclock Spark", faction: "robot", kind: "spell", cost: 2, atk: 0, hp: 0, rarity: "basic", set: "kage", tags: [], play: { t: "overclock" }, text: "A Quorin ally gets +2/+1 and can attack this turn." },
  { id: "kg-cold-seal", name: "Cold Seal", faction: "robot", kind: "spell", cost: 2, atk: 0, hp: 0, rarity: "basic", set: "kage", tags: [], play: { t: "healSelf", n: 2 }, text: "Heal 2." },
  { id: "kg-prism-sentry", name: "Prism Sentry", faction: "robot", kind: "unit", cost: 3, atk: 2, hp: 4, rarity: "basic", set: "kage", tags: [], text: "It does not blink." },
  { id: "kg-lens-blade", name: "Lens Blade", faction: "robot", kind: "unit", cost: 3, atk: 3, hp: 2, rarity: "basic", set: "kage", tags: [], text: "A clean hole, then silence." },
  { id: "kg-ward-plate", name: "Ward Plate", faction: "robot", kind: "trap", cost: 2, atk: 0, hp: 0, rarity: "basic", set: "kage", tags: [], trap: "firewall", text: "Trap. When they attack: prevent the next 4 damage to you." },
  { id: "kg-null-hood", name: "Null Hood", faction: "robot", kind: "unit", cost: 4, atk: 2, hp: 6, rarity: "rare", set: "kage", tags: ["bulwark"], text: "Bulwark." },
  { id: "kg-apex-shadow", name: "Apex Shadow", faction: "robot", kind: "unit", cost: 4, atk: 4, hp: 3, rarity: "rare", set: "kage", tags: [], text: "The array leans in." },
  { id: "kg-hex-lance", name: "Hex Lance", faction: "robot", kind: "spell", cost: 3, atk: 0, hp: 0, rarity: "rare", set: "kage", tags: [], play: { t: "hit", n: 3 }, text: "Deal 3 to a unit or a player." },
  { id: "kg-still-array", name: "Still Array", faction: "robot", kind: "trap", cost: 2, atk: 0, hp: 0, rarity: "rare", set: "kage", tags: [], trap: "horizon", text: "Trap. When they attack: deal 2 to an attacker and freeze it." },
  { id: "kg-apex-kage", name: "APEX of the Quiet Hour", faction: "robot", kind: "unit", cost: 7, atk: 4, hp: 7, rarity: "legendary", set: "kage", tags: [], play: { t: "apex" }, text: "Play: your other Quorin get +0/+1." },

  { id: "kg-cinder-imp", name: "Cinder Imp", faction: "demon", kind: "unit", cost: 1, atk: 2, hp: 1, rarity: "basic", set: "kage", tags: [], play: { t: "loseHp", n: 1 }, text: "Play: lose 1 life." },
  { id: "kg-ash-step", name: "Ash Step", faction: "demon", kind: "unit", cost: 2, atk: 2, hp: 2, rarity: "basic", set: "kage", tags: [], text: "Ember eyes under a black hood." },
  { id: "kg-ember-cloak", name: "Ember Cloak", faction: "demon", kind: "unit", cost: 2, atk: 2, hp: 1, rarity: "basic", set: "kage", tags: [], text: "The cloth smolders and does not burn." },
  { id: "kg-ash-knight", name: "Ash Knight", faction: "demon", kind: "unit", cost: 2, atk: 3, hp: 1, rarity: "basic", set: "kage", tags: [], text: "Hits, then the dark takes the rest." },
  { id: "kg-pact-spark", name: "Pact Spark", faction: "demon", kind: "spell", cost: 2, atk: 0, hp: 0, rarity: "basic", set: "kage", tags: [], play: { t: "hit", n: 2 }, text: "Deal 2 to a unit or a player." },
  { id: "kg-hell-seal", name: "Hell Seal", faction: "demon", kind: "spell", cost: 2, atk: 0, hp: 0, rarity: "basic", set: "kage", tags: [], play: { t: "hit", n: 3 }, text: "Deal 3 to a unit or a player." },
  { id: "kg-pact-ink", name: "Pact Ink", faction: "demon", kind: "spell", cost: 1, atk: 0, hp: 0, rarity: "basic", set: "kage", tags: [], play: { t: "draw", n: 2, lose: 2 }, text: "Draw 2. Lose 2 life. You cannot drop below 1 this way." },
  { id: "kg-brand-hood", name: "Brand Hood", faction: "demon", kind: "unit", cost: 3, atk: 3, hp: 2, rarity: "basic", set: "kage", tags: [], text: "A horned shadow with a short blade." },
  { id: "kg-blood-cut", name: "Blood Cut", faction: "demon", kind: "unit", cost: 3, atk: 4, hp: 2, rarity: "basic", set: "kage", tags: [], text: "Hits hard. Does not stay." },
  { id: "kg-soul-wire", name: "Soul Wire", faction: "demon", kind: "trap", cost: 2, atk: 0, hp: 0, rarity: "basic", set: "kage", tags: [], trap: "soul", text: "Trap. When any unit dies: heal 3 and this banishes." },
  { id: "kg-hexbrand-kage", name: "Hexbrand Shinobi", faction: "demon", kind: "unit", cost: 3, atk: 3, hp: 3, rarity: "rare", set: "kage", tags: ["drain"], text: "Drain. Damage this deals to a player heals you." },
  { id: "kg-duchess-kage", name: "Duchess of Ash", faction: "demon", kind: "unit", cost: 5, atk: 5, hp: 4, rarity: "rare", set: "kage", tags: [], play: { t: "draw", n: 1, lose: 2 }, text: "Play: lose 2 life and draw 1. You cannot drop below 1 this way." },
  { id: "kg-pit-flame", name: "Pit Flame", faction: "demon", kind: "spell", cost: 3, atk: 0, hp: 0, rarity: "rare", set: "kage", tags: [], play: { t: "hit", n: 3 }, text: "Deal 3 to a unit or a player." },
  { id: "kg-soul-seal", name: "Soul Seal", faction: "demon", kind: "trap", cost: 2, atk: 0, hp: 0, rarity: "rare", set: "kage", tags: [], trap: "soul", text: "Trap. When any unit dies: heal 3 and this banishes." },
  { id: "kg-tyrant-kage", name: "Tyrant of the Black Hour", faction: "demon", kind: "unit", cost: 7, atk: 6, hp: 6, rarity: "legendary", set: "kage", tags: ["crush"], text: "Crush. Extra damage past a blocker hits the player." },

  { id: "kg-pale-step", name: "Pale Step", faction: "veil", kind: "unit", cost: 1, atk: 1, hp: 1, rarity: "basic", set: "kage", tags: [], deathHeal: 1, text: "When this dies, you heal 1. No seal claims it." },
  { id: "kg-quiet-hand", name: "Quiet Hand", faction: "veil", kind: "unit", cost: 1, atk: 1, hp: 2, rarity: "basic", set: "kage", tags: [], text: "A faceless cloth. No crest." },
  { id: "kg-silver-blade", name: "Silver Blade", faction: "veil", kind: "unit", cost: 2, atk: 2, hp: 1, rarity: "basic", set: "kage", tags: ["haste"], text: "Haste." },
  { id: "kg-no-crest", name: "No Crest", faction: "veil", kind: "unit", cost: 2, atk: 2, hp: 2, rarity: "basic", set: "kage", tags: [], text: "Steel with the mark filed off." },
  { id: "kg-slip-seal", name: "Slip Seal", faction: "veil", kind: "spell", cost: 1, atk: 0, hp: 0, rarity: "basic", set: "kage", tags: [], play: { t: "grantHaste" }, text: "An ally unit gains haste this turn and can attack immediately." },
  { id: "kg-toll-cut", name: "Toll Cut", faction: "veil", kind: "spell", cost: 1, atk: 0, hp: 0, rarity: "basic", set: "kage", tags: [], play: { t: "hit", n: 2 }, text: "Deal 2 to a unit or a player." },
  { id: "kg-road-ward", name: "Road Ward", faction: "veil", kind: "unit", cost: 3, atk: 1, hp: 4, rarity: "basic", set: "kage", tags: ["bulwark"], text: "Bulwark." },
  { id: "kg-ash-walk", name: "Ash Walk", faction: "veil", kind: "unit", cost: 3, atk: 2, hp: 3, rarity: "basic", set: "kage", tags: [], text: "It does not take a side." },
  { id: "kg-nameless-step", name: "Nameless Step", faction: "veil", kind: "unit", cost: 3, atk: 2, hp: 2, rarity: "basic", set: "kage", tags: [], text: "The road keeps its own assassins." },
  { id: "kg-cross-mark", name: "Cross Mark", faction: "veil", kind: "trap", cost: 2, atk: 0, hp: 0, rarity: "basic", set: "kage", tags: [], trap: "cross", text: "Trap. When they attack: deal 2 to an attacker." },
  { id: "kg-pilgrim-kage", name: "Night Pilgrim", faction: "veil", kind: "unit", cost: 3, atk: 3, hp: 2, rarity: "rare", set: "kage", tags: ["haste"], text: "Haste. Can attack the turn it enters." },
  { id: "kg-faceless", name: "The Faceless", faction: "veil", kind: "unit", cost: 4, atk: 3, hp: 4, rarity: "rare", set: "kage", tags: [], text: "No seal. Just the cut." },
  { id: "kg-silver-mend", name: "Silver Mend", faction: "veil", kind: "spell", cost: 3, atk: 0, hp: 0, rarity: "rare", set: "kage", tags: [], play: { t: "healSelf", n: 4 }, text: "Heal 4." },
  { id: "kg-horizon-seal", name: "Horizon Seal", faction: "veil", kind: "trap", cost: 2, atk: 0, hp: 0, rarity: "rare", set: "kage", tags: [], trap: "horizon", text: "Trap. When they attack: deal 2 to an attacker and freeze it." },
  { id: "kg-veil-kage", name: "The Veil Unmasked", faction: "veil", kind: "unit", cost: 7, atk: 5, hp: 6, rarity: "legendary", set: "kage", tags: ["haste"], play: { t: "healSelf", n: 2 }, text: "Haste. Play: heal 2. The sixth seal, wearing no face." },
];
