/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVeilforgeGiftRouteImport } from './routes/api/veilforge/gift'
import { Route as ApiVeilforgeHealthRouteImport } from './routes/api/veilforge/health'
import { Route as ApiVeilforgeProfileRouteImport } from './routes/api/veilforge/profile'
import { Route as ApiVeilforgeQueueRouteImport } from './routes/api/veilforge/queue'
import { Route as ApiVeilforgeRewardRouteImport } from './routes/api/veilforge/reward'
import { Route as ApiVeilforgeStatusRouteImport } from './routes/api/veilforge/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVeilforgeGiftRoute = ApiVeilforgeGiftRouteImport.update({
  id: '/api/veilforge/gift',
  path: '/api/veilforge/gift',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVeilforgeHealthRoute = ApiVeilforgeHealthRouteImport.update({
  id: '/api/veilforge/health',
  path: '/api/veilforge/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVeilforgeProfileRoute = ApiVeilforgeProfileRouteImport.update({
  id: '/api/veilforge/profile',
  path: '/api/veilforge/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVeilforgeQueueRoute = ApiVeilforgeQueueRouteImport.update({
  id: '/api/veilforge/queue',
  path: '/api/veilforge/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVeilforgeRewardRoute = ApiVeilforgeRewardRouteImport.update({
  id: '/api/veilforge/reward',
  path: '/api/veilforge/reward',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVeilforgeStatusRoute = ApiVeilforgeStatusRouteImport.update({
  id: '/api/veilforge/status',
  path: '/api/veilforge/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/veilforge/gift': typeof ApiVeilforgeGiftRoute
  '/api/veilforge/health': typeof ApiVeilforgeHealthRoute
  '/api/veilforge/profile': typeof ApiVeilforgeProfileRoute
  '/api/veilforge/queue': typeof ApiVeilforgeQueueRoute
  '/api/veilforge/reward': typeof ApiVeilforgeRewardRoute
  '/api/veilforge/status': typeof ApiVeilforgeStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/veilforge/gift': typeof ApiVeilforgeGiftRoute
  '/api/veilforge/health': typeof ApiVeilforgeHealthRoute
  '/api/veilforge/profile': typeof ApiVeilforgeProfileRoute
  '/api/veilforge/queue': typeof ApiVeilforgeQueueRoute
  '/api/veilforge/reward': typeof ApiVeilforgeRewardRoute
  '/api/veilforge/status': typeof ApiVeilforgeStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/veilforge/gift': typeof ApiVeilforgeGiftRoute
  '/api/veilforge/health': typeof ApiVeilforgeHealthRoute
  '/api/veilforge/profile': typeof ApiVeilforgeProfileRoute
  '/api/veilforge/queue': typeof ApiVeilforgeQueueRoute
  '/api/veilforge/reward': typeof ApiVeilforgeRewardRoute
  '/api/veilforge/status': typeof ApiVeilforgeStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/veilforge/gift'
    | '/api/veilforge/health'
    | '/api/veilforge/profile'
    | '/api/veilforge/queue'
    | '/api/veilforge/reward'
    | '/api/veilforge/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/veilforge/gift'
    | '/api/veilforge/health'
    | '/api/veilforge/profile'
    | '/api/veilforge/queue'
    | '/api/veilforge/reward'
    | '/api/veilforge/status'
  id:
    | '__root__'
    | '/'
    | '/api/veilforge/gift'
    | '/api/veilforge/health'
    | '/api/veilforge/profile'
    | '/api/veilforge/queue'
    | '/api/veilforge/reward'
    | '/api/veilforge/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiVeilforgeGiftRoute: typeof ApiVeilforgeGiftRoute
  ApiVeilforgeHealthRoute: typeof ApiVeilforgeHealthRoute
  ApiVeilforgeProfileRoute: typeof ApiVeilforgeProfileRoute
  ApiVeilforgeQueueRoute: typeof ApiVeilforgeQueueRoute
  ApiVeilforgeRewardRoute: typeof ApiVeilforgeRewardRoute
  ApiVeilforgeStatusRoute: typeof ApiVeilforgeStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/veilforge/gift': {
      id: '/api/veilforge/gift'
      path: '/api/veilforge/gift'
      fullPath: '/api/veilforge/gift'
      preLoaderRoute: typeof ApiVeilforgeGiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/veilforge/health': {
      id: '/api/veilforge/health'
      path: '/api/veilforge/health'
      fullPath: '/api/veilforge/health'
      preLoaderRoute: typeof ApiVeilforgeHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/veilforge/profile': {
      id: '/api/veilforge/profile'
      path: '/api/veilforge/profile'
      fullPath: '/api/veilforge/profile'
      preLoaderRoute: typeof ApiVeilforgeProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/veilforge/queue': {
      id: '/api/veilforge/queue'
      path: '/api/veilforge/queue'
      fullPath: '/api/veilforge/queue'
      preLoaderRoute: typeof ApiVeilforgeQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/veilforge/reward': {
      id: '/api/veilforge/reward'
      path: '/api/veilforge/reward'
      fullPath: '/api/veilforge/reward'
      preLoaderRoute: typeof ApiVeilforgeRewardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/veilforge/status': {
      id: '/api/veilforge/status'
      path: '/api/veilforge/status'
      fullPath: '/api/veilforge/status'
      preLoaderRoute: typeof ApiVeilforgeStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiVeilforgeGiftRoute: ApiVeilforgeGiftRoute,
  ApiVeilforgeHealthRoute: ApiVeilforgeHealthRoute,
  ApiVeilforgeProfileRoute: ApiVeilforgeProfileRoute,
  ApiVeilforgeQueueRoute: ApiVeilforgeQueueRoute,
  ApiVeilforgeRewardRoute: ApiVeilforgeRewardRoute,
  ApiVeilforgeStatusRoute: ApiVeilforgeStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
